### ISSUE TITLE
Long build times in CI on older compilers

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/hybrid-array#47]
I just noticed `hybrid-array` takes 3m to build on 1.65: https://github.com/RustCrypto/hybrid-array/actions/runs/7923269699/job/21632628872

However, it takes 2s on stable (1.75): https://github.com/RustCrypto/hybrid-array/actions/runs/7923269699/job/21632630167

**Comment by tarcieri** [comment]
I wasn't able to reproduce this locally with an older compiler:

```
$ rustc --version
rustc 1.65.0 (897e37553 2022-11-02)
$ cargo clean
$ cargo build --no-default-features --target thumbv7em-none-eabi
   Compiling typenum v1.17.0
   Compiling hybrid-array v0.2.0-rc.5 (/Users/tarcieri/src/RustCrypto/hybrid-array)
    Finished dev [unoptimized + debuginfo] target(s) in 1.31s
```

**Comment by tarcieri** [comment]
I wonder if this has nothing to do with the crate itself and is in fact the time it takes to update the legacy Cargo index, since it's not using the sparse index

**Comment by newpavlov** [comment]
>the time it takes to update the legacy Cargo index

In theory, this should be handled by `cargo-cache` which is used in the workflow.

**Comment by tarcieri** [comment]
Is the cache potentially stale?

**Comment by tarcieri** [comment]
It's definitely time spent updating the crates.io index. I just observed it watching the build:

<img width="551" alt="Screenshot 2024-02-16 at 7 39 47 AM" src="https://github.com/RustCrypto/hybrid-array/assets/797/39400908-8f03-44b1-ba82-5afac49b0f02">

Going to close this as I was primarily worried `hybrid-array` was doing something which caused actual time compiling the crate to last this long. Not too worried about the legacy crates.io index.
