### ISSUE TITLE
ArraySize definitions for Post-Quantum signature sizes

### ISSUE THREAD

**Issue by tjade273** [RustCrypto/hybrid-array#55]
The FIPS SLH-DSA and ML-DSA draft standards have signature sizes which are very large in the former and odd sizes in the latter, so neither has signature sizes covered by the current ArraySize implementations

SLH-DSA has signatures of lengths:
* 7856 
* 17088
* 16224
* 35664
* 29792
* 49856

ML-DSA has signatures of lengths:
* 2420
* 3293
* 4595

ML-DSA also has private keys of size 4864 for category 5.

I don't know if you want to set a precedent for people requesting random extra ArraySize impls, but these would be useful for writing clean no-std implementations of the new PQ schemes.

**Comment by tarcieri** [comment]
Ugh, well here I thought I had everything working with some consistent rules for sizes, but 3293 and 4595 definitely violate that. It's a bit frustrating given `hybrid-array`'s tradeoffs versus `generic-array` where we do need to write `ArraySize` impls for each size.

That said, I guess we can just take one off sizes to support by request.
